---
# Initial Server Setup
web_user: warden

# MySQL Setup
mysql_root_password: root
mysql_app_db: arbor
mysql_app_user: stonemason
mysql_app_pass: mysql

# Web Server Setup
http_host: arbor.local
remote_www_root: /var/www
app_root_dir: arbor
document_root: "{{ remote_www_root }}/{{ app_root_dir }}/public"

# Laravel Env Variables
app_name: Arbor
app_env: lima  # Set environment to lima for the Lima VM
app_debug: true
app_url: "http://{{ http_host }}"
db_host: localhost
db_port: 3306
db_database: "{{ mysql_app_db }}"
db_user: "{{ mysql_app_user }}"
db_pass: "{{ mysql_app_pass }}"

# Define local paths for macOS host where certificates will be fetched
local_ca_cert_path: "{{ lookup('env', 'HOME') }}/Downloads/lima-ca.pem"
local_server_cert_path: "{{ lookup('env', 'HOME') }}/Downloads/lima-server.pem"
local_server_key_path: "{{ lookup('env', 'HOME') }}/Downloads/lima-server.key"

# Define remote paths on Lima VM
ca_cert_path: "/etc/ssl/certs/lima-ca.pem"
ca_key_path: "/etc/ssl/private/lima-ca.key"
server_cert_path: "/etc/ssl/certs/lima-server.pem"
server_key_path: "/etc/ssl/private/lima-server.key"
server_csr_path: "/etc/ssl/certs/lima-server.csr"

# Define temporary paths for transfer
temp_ca_cert_path: "/tmp/lima-ca.pem"
temp_server_cert_path: "/tmp/lima-server.pem"
temp_server_key_path: "/tmp/lima-server.key"

