---
- name: Install Redis
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Ensure Redis is running
  service:
    name: redis-server
    state: started
    enabled: yes
