---
- name: Import Nodesource RPM key.
  rpm_key:
    key: https://rpm.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add Nodesource repositories for Node.js.
  yum:
    name: "https://rpm.nodesource.com/pub_{{ nodejs_version }}/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm"
    state: present
  when: ansible_distribution_major_version | int >= 7
  register: node_repo

- name: Update package cache if repo was added.
  yum:
    update_cache: true
  when: node_repo is changed
  tags: ['skip_ansible_lint']

- name: Ensure Node.js AppStream module is disabled (CentOS 8+).
  command: yum module disable -y nodejs
  register: module_disable
  changed_when: "'Nothing to do.' not in module_disable.stdout"
  when: ansible_distribution_major_version | int >= 8

- name: Ensure Node.js and npm are installed.
  yum:
    name: "nodejs-{{ nodejs_version | regex_replace('x', '') }}*"
    state: present
    enablerepo: nodesource
