- name: Install prerequisites
  hosts: web
  remote_user: "{{ sudo_user }}"
  gather_facts: false
  tasks:
    - name: Ensure Python 3.8 is installed
      raw: sudo apt-get update && sudo apt-get install -y python3.8
      changed_when: false

    - name: Ensure Python 3 points to Python 3.8
      raw: sudo ln -sf /usr/bin/python3.8 /usr/bin/python3
      changed_when: false

    - name: Gather Facts
      setup:

    - name: Add repository for PHP 8.2
      raw: sudo add-apt-repository ppa:ondrej/php -y && sudo apt-get update
      changed_when: false

- name: Sudo user Creation
  hosts: web
  remote_user: "{{ sudo_user }}"
  tasks:
    - name: Create sudo user
      ansible.builtin.user:
        name: "{{ sudo_user }}"
        password: "{{ upassword | password_hash('sha512') }}"
        state: present
        create_home: yes
        groups: "sudo"
        append: yes
        shell: /bin/bash
        comment: "Comment"
    - name: Set up authorized keys for the sudo user
      ansible.builtin.authorized_key:
        user: "{{ sudo_user }}"
        key: "{{ github_keys }}"
      when: not ansible_check_mode

- name: Web user creation
  hosts: web
  remote_user: "{{ sudo_user }}"
  tasks:
    - name: Create web user
      ansible.builtin.user:
        name: "{{ web_user }}"
        state: present
        create_home: yes
        groups: "www-data"
        append: yes
        shell: /bin/bash
        comment: "Comment"
    - name: Set up authorized keys for the web user
      ansible.builtin.authorized_key:
        user: "{{ web_user }}"
        key: "{{ github_keys }}"
      when: not ansible_check_mode
    - name: Ensure .bashrc exists for the web user
      ansible.builtin.file:
        path: "/home/{{ web_user }}/.bashrc"
        state: touch
        owner: "{{ web_user }}"
        group: "www-data"
        mode: '0644'
    - name: Add Composer to path
      ansible.builtin.lineinfile:
        dest: "/home/{{ web_user }}/.bashrc"
        state: present
        line: 'export PATH="$PATH:$HOME/.composer/vendor/bin"'
        owner: "{{ web_user }}"
        group: "www-data"
        mode: '0644'

- name: LEMP Provisioning
  hosts: web
  remote_user: "{{ sudo_user }}"
  vars_files:
    - vars/main.yml
  roles:
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.certbot }
    - { role: geerlingguy.php }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.php-mysql }
    - { role: geerlingguy.memcached }
    - { role: geerlingguy.git }
    - { role: geerlingguy.composer }
    - { role: geerlingguy.nodejs }
    - { role: geerlingguy.redis }

- name: Laravel Homebase Setup
  hosts: web
  remote_user: "{{ sudo_user }}"
  tasks:
    - name: Project Folder Creation
      ansible.builtin.file:
        dest: /var/www/{{ domain }}
        mode: '2755'
        state: directory
        owner: web
        group: www-data

- name: SSL Certificate Setup
  hosts: web
  remote_user: "{{ sudo_user }}"
  tasks:
    - name: Install Certbot Plugin
      ansible.builtin.package:
        name: python3-certbot-nginx
        state: present

    - name: Generate SSL certificates using Certbot
      command: certbot --nginx -n -d {{ domain }} --email {{ certbot_email }} --redirect --agree-tos
      when: certbot_email is defined