---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false
    php_enable_php_fpm: true
    php_memory_limit: "192M"
    php_enablerepo: "remi,remi-php82"
    php_install_recommends: false

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: geerlingguy.repo-remi
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution != 'Fedora'
    - role: geerlingguy.php

  post_tasks:
    - name: Confirm PHP configuration is correct.
      shell: php -i | grep 'memory_limit.*192'
      changed_when: false
