---
- name: Install Node.js
  apt:
    name: nodejs
    state: present
  tags: nodejs

- name: Install npm
  apt:
    name: npm
    state: present
  tags: npm

- name: Install build-essential (for building native addons)
  apt:
    name: build-essential
    state: present
  tags: nodejs
