---
- name: Install Prerequisites
  apt: 
    name: aptitude 
    update_cache: yes 
    state: latest 
    force_apt_get: yes

# Sudo Group Setup
- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

# User + Key Setup
- name: Create a new regular user with sudo privileges
  user:
    name: "{{ web_user }}"
    state: present
    groups: sudo
    append: true
    create_home: true
    shell: /bin/bash

# Ensure ownership of user's home directory
- name: Set ownership of web user home directory
  file:
    path: "/home/{{ web_user }}"
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    recurse: yes

# SSH Key Setup
- name: Check for id_rsa.pub
  set_fact:
    copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  when: lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub', errors='ignore') is not none

- name: Check for id_ed25519.pub if id_rsa.pub not found
  set_fact:
    copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
  when: copy_local_key is not defined or copy_local_key == ''

- name: Set authorized key for web user
  authorized_key:
    user: "{{ web_user }}"
    state: present
    key: "{{ copy_local_key }}"

- name: Disable password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'

# Ensure .bashrc file exists
- name: Ensure .bashrc file exists for web user
  file:
    path: "/home/{{ web_user }}/.bashrc"
    state: touch
    owner: "{{ web_user }}"
    group: "{{ web_user }}"

# Add alias ll to .bashrc
- name: Add ll alias to .bashrc for web user
  lineinfile:
    path: "/home/{{ web_user }}/.bashrc"
    state: present
    regexp: '^alias ll='
    line: "alias ll='ls -alF'"
  become: false

# Ensure .profile file exists
- name: Ensure .profile file exists for web user
  file:
    path: "/home/{{ web_user }}/.profile"
    state: touch
    owner: "{{ web_user }}"
    group: "{{ web_user }}"

# Add alias ll to .profile
- name: Add ll alias to .profile for web user
  lineinfile:
    path: "/home/{{ web_user }}/.profile"
    state: present
    regexp: '^alias ll='
    line: "alias ll='ls -alF'"

# Install Packages
- name: Update apt
  apt: 
    update_cache: yes

- name: Install required system packages
  apt:
    name: "{{ sys_packages }}"
    state: latest

# Install acl if missing
- name: Install acl for setfacl command
  apt:
    name: acl
    state: present

# UFW Setup
- name: UFW - Allow SSH connections
  ufw:
    rule: allow
    name: OpenSSH

- name: UFW - Deny all other incoming traffic by default
  ufw:
    state: enabled
    policy: deny
    direction: incoming
